### ISSUE TITLE
[Bug] API version not specified

### ISSUE THREAD

**Issue by Possemaster** [NicoNekoDev/AstralBooks#29]
### Information
Full output of `/npcbook about`:
[INFO] ....>.... +----------------------+
[INFO] ....
[INFO] .... <+ CitizensBooks +>
[INFO] .... Version: 2.5.2
[INFO] .... Auhtor: nicuch
[INFO] ....
[INFO] .... +----------------------+

### Details
Installed latest plugin
Started server
Console reads: ''[WARNING] .... Plugin CitizensBooks v2.5.2 does not specify an api-version.''
No issues with the plugin so far, just a ease of mind QOL fix for Server admins

MC version 1.14.4
PaperMC 199
CitizensBooks v2.5.2

**Comment by NicoNekoDev** [comment]
That's just an warning, not a bug, also if I specify the api-version, the plugin might break for version 1.13. Just ignore the warning :)

**Comment by Possemaster** [comment]
Yes it is a bug, not game breaking but unintended and easily fixed. I reported this also with 5 other devs and they fixed it under 24 hours.
Just set the flag on 1.13 in plugin.yml and it will work for 1.13 and up. 1.12.2 and lower do not use the flag. You just have to specify it, it will not break anything.

So, the downsides of not having the api-version is..

It slows down the load time because Bukkit/spigot applies special mapping compatibilty things that reads, parses and processes class files

In 1.14 (not 1.13 though) the plugin will give a warning like the issue specified in here - "Plugin x does not specify an api-version."

The plugin will show extra * character at the end of the name in 1.13 or 1.14. This applies to every location, e.g: "Enabling citizensbook*", "Disabling citizensbook*", "Plugins(1): citizensbook*" etc.

Also the warning will become an error in the future. It's always great to fix every error and warning in your server log. Sure, I can fix manually, the code is already compatible with 1.13 and 1.14, so why not fix it

**Comment by NicoNekoDev** [comment]
"This will signal to the server that your plugin has been coded with a specific server version in mind, and that it should not apply any sort of backwards compatibility measures. As a result you will also need to make sure that you have programmed your code to account for reading of older configurations, data, etc... .Each server version can decide how compatibility is achieved, unknown or future versions will prevent the plugin from enabling. As of the 1.14 release, the api-version 1.13 is still allowed - however future versions may drop backwards support based on this version."
Source: https://www.spigotmc.org/wiki/plugin-yml/

My plugin have not a specific version in mind, it have multiple versions, from 1.8 to 1.14. I can allways drop support for those versions and make them in separate files, but this is time consuming, like fixing bugs and adding features.

"It slows down the load time because Bukkit/spigot applies special mapping compatibilty things that reads, parses and processes class files" can you give me the source for this? As I remember, spigot does this anyway, it's called "LEGACY CODE", and it doesn't affect load time.

**Comment by Possemaster** [comment]
True, but this is ONLY for 1.13 and up.

> The version of the API you want to use.
> 1.13 and 1.14 are available versions

1.12.2 and lower are NOT using this api-version statement in plugin.yml.
This is a Spigot thing and for 1.13 and UP.
So if you set it to 1.13 NOTHING will change now. as 1.8 and up to 1.12.2 will NOT even use this. 
And 1.13 and up will use 1.13 api version which works fine.
The only possible issue is when 1.15 arrives it is possible it does not support a lower api version. But than you would have an issue anyway as you did NOT clarify the api-version.

I only state it here as I already fixed it for myself but I would hate to see someone forking your work and make it "compatible"

And PS LEGACY CODE is definitly slower. Not for a single plugin but it will ADD up if anyone is sloppy in not clarifying stuff in code.

**Comment by NicoNekoDev** [comment]
"It slows down the load time because Bukkit/spigot applies special mapping compatibilty things that reads, parses and processes class files" Asking again... can you give me the source for this? If this is true, I'm gonna put the api-version in the final product, otherwise I will not.

"I would hate to see someone forking your work and make it 'compatible'" Thanks for worrying, but it is compatible with all versions from 1.8 to 1.14. What you don't understand is that the server don't slow down because of this plugin, and there's no good reason for THIS plugin in particular to have api-version specified.

PS: anyway, I will remove backwards compability when 1.15 is out, and adding all the features I wanted to add.
