### ISSUE TITLE
CitizensBooks Causing Server to Crash

### ISSUE THREAD

**Issue by zaccieslak** [NicoNekoDev/AstralBooks#32]
![image](https://user-images.githubusercontent.com/51010650/69263068-32915880-0b8a-11ea-8272-6f6868b06b84.png)

So I guess that CitizensBooks is making my server shutdown upon startup. I'm not sure why, but it's the only plugin that's force-stopping my server.

**Comment by zaccieslak** [comment]
I see the update - I'll try it out! Sorry for this.

**Comment by NicoNekoDev** [comment]
This happened because after the update is downloaded, is shutting down the server so the plugin is reloaded. The old version is not deleted, and you have 2 versions of the same plugin. Because production servers have a cpanel or something like this, the server is restarted by cpanel. In my testing... if I have 2 plugins the same, the result is an error `[Server thread/ERROR]: Ambiguous plugin name `CitizensBooks' for files `plugins\CitizensBooks-2.5.3.jar' and `plugins\CitizensBooks-2.5.2.jar' in `plugins'` and then the highest version is selected (probably because files are sorted by the OS). I guess because there are different OS, its not picking the updated version first, and its loading the same old version, that start to download the newest version again, and shut-down itself again, and the loop continues.
I removed the shut-down, pushed the update, but for servers that use the old version, or it already have the update, it's still gonna be problematic until they remove the old version(s) from plugins.
I'm going to leave this open for one week just so I be sure no one report it again.

How to fix your server if it's keeping crashing:
1) go to "plugins" folder
2) remove any CitizensBooks jars found
3) download and install the latest version from spigot.
4) (optional) go to "plugins/CitizensBooks" folder, open config.yml and disable auto-updater by setting in the config "auto_update: false"
